"""initial schema

Revision ID: bda609bd4cea
Revises: 
Create Date: 2026-08-31 12:52:56.167483
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'bda609bd4cea'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('contact_email', sa.String(length=160), nullable=False),
    sa.Column('contract_tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('part_master',
    sa.Column('part_code', sa.String(length=24), nullable=False),
    sa.Column('part_name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('design_life_km', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('labour_hours', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('part_code')
    )
    op.create_table('rules',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_code', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('days_to_alert', sa.Float(), nullable=False),
    sa.Column('sample_failures', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_code'], ['part_master.part_code'], ),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('part_code', 'version', name='uq_rule_part_version')
    )
    op.create_index('ix_rules_part_active', 'rules', ['part_code', 'is_active'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle_master',
    sa.Column('vin', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('variant', sa.String(length=60), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('total_km_driven', sa.Integer(), nullable=False),
    sa.Column('avg_km_per_day', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('vin')
    )
    op.create_index('ix_vehicle_customer_status', 'vehicle_master', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_vehicle_master_customer_id'), 'vehicle_master', ['customer_id'], unique=False)
    op.create_index('ix_vehicle_model', 'vehicle_master', ['model'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_table('job_cards',
    sa.Column('job_card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=24), nullable=False),
    sa.Column('part_code', sa.String(length=24), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('odometer_reading', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('replaced', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('downtime_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['part_code'], ['part_master.part_code'], ),
    sa.ForeignKeyConstraint(['vin'], ['vehicle_master.vin'], ),
    sa.PrimaryKeyConstraint('job_card_id')
    )
    op.create_index('ix_jobcard_type_date', 'job_cards', ['event_type', 'event_date'], unique=False)
    op.create_index('ix_jobcard_vin_part_date', 'job_cards', ['vin', 'part_code', 'event_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=24), nullable=False),
    sa.Column('part_code', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['part_code'], ['part_master.part_code'], ),
    sa.ForeignKeyConstraint(['vin'], ['vehicle_master.vin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_status_audience', 'notifications', ['status', 'audience'], unique=False)
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=24), nullable=False),
    sa.Column('part_code', sa.String(length=24), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(length=8), nullable=False),
    sa.Column('health_index', sa.Float(), nullable=False),
    sa.Column('window_from_days', sa.Integer(), nullable=False),
    sa.Column('window_to_days', sa.Integer(), nullable=False),
    sa.Column('rul_km', sa.Float(), nullable=False),
    sa.Column('rul_days', sa.Float(), nullable=False),
    sa.Column('model_confidence', sa.Float(), nullable=False),
    sa.Column('degradation_trend', sa.Float(), nullable=False),
    sa.Column('top_signal', sa.String(length=48), nullable=True),
    sa.Column('top_signal_share', sa.Float(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.String(length=255), nullable=True),
    sa.Column('drivers', sa.JSON(), nullable=True),
    sa.Column('trend', sa.JSON(), nullable=True),
    sa.Column('curve', sa.JSON(), nullable=True),
    sa.Column('estimated_cost_impact', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('computed_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['part_code'], ['part_master.part_code'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.ForeignKeyConstraint(['vin'], ['vehicle_master.vin'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin', 'part_code', name='uq_prediction_vin_part')
    )
    op.create_index('ix_prediction_part', 'predictions', ['part_code'], unique=False)
    op.create_index('ix_prediction_rul', 'predictions', ['rul_days'], unique=False)
    op.create_index('ix_prediction_tier', 'predictions', ['risk_tier'], unique=False)
    op.create_table('rule_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=48), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'signal', name='uq_rulesignal')
    )
    op.create_table('telematics_weekly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=24), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_km', sa.Float(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('coolant_temp_variance', sa.Float(), nullable=False),
    sa.Column('oil_pressure_dips', sa.Float(), nullable=False),
    sa.Column('battery_voltage_sag', sa.Float(), nullable=False),
    sa.Column('dtc_recurrence_rate', sa.Float(), nullable=False),
    sa.Column('harsh_braking_frequency', sa.Float(), nullable=False),
    sa.Column('overload_duty_share', sa.Float(), nullable=False),
    sa.Column('high_rpm_dwell_time', sa.Float(), nullable=False),
    sa.Column('short_trip_ratio', sa.Float(), nullable=False),
    sa.Column('idle_time_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vin'], ['vehicle_master.vin'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin', 'week_start_date', name='uq_telematics_vin_week')
    )
    op.create_index('ix_telematics_week', 'telematics_weekly', ['week_start_date'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=24), nullable=False),
    sa.Column('part_code', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['part_code'], ['part_master.part_code'], ),
    sa.ForeignKeyConstraint(['vin'], ['vehicle_master.vin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_customer_id'), 'work_orders', ['customer_id'], unique=False)
    op.create_table('warranty_claims',
    sa.Column('claim_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=24), nullable=False),
    sa.Column('part_code', sa.String(length=24), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.job_card_id'], ),
    sa.ForeignKeyConstraint(['part_code'], ['part_master.part_code'], ),
    sa.ForeignKeyConstraint(['vin'], ['vehicle_master.vin'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranty_claims')
    op.drop_index(op.f('ix_work_orders_customer_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index('ix_telematics_week', table_name='telematics_weekly')
    op.drop_table('telematics_weekly')
    op.drop_table('rule_signals')
    op.drop_index('ix_prediction_tier', table_name='predictions')
    op.drop_index('ix_prediction_rul', table_name='predictions')
    op.drop_index('ix_prediction_part', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_index('ix_notification_status_audience', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_jobcard_vin_part_date', table_name='job_cards')
    op.drop_index('ix_jobcard_type_date', table_name='job_cards')
    op.drop_table('job_cards')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_vehicle_model', table_name='vehicle_master')
    op.drop_index(op.f('ix_vehicle_master_customer_id'), table_name='vehicle_master')
    op.drop_index('ix_vehicle_customer_status', table_name='vehicle_master')
    op.drop_table('vehicle_master')
    op.drop_table('users')
    op.drop_index('ix_rules_part_active', table_name='rules')
    op.drop_table('rules')
    op.drop_table('part_master')
    op.drop_table('customers')
    # ### end Alembic commands ###
